[package]
edition = { workspace = true }
name = "onboarding"
publish = { workspace = true }
version = "0.1.0"

[dependencies]
async-trait = { workspace = true }
axum = { workspace = true }
axum-extra = { version = "0.9.2", features = ["typed-header"] }
axum-macros = { workspace = true }
isocountry = { workspace = true }
once_cell = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
tracing = { workspace = true }
utoipa = { workspace = true }

# path dependencies
account = { workspace = true }
argon2 = { workspace = true }
authn_authz = { workspace = true }
bdk_utils = { workspace = true }
comms_verification = { workspace = true }
database = { workspace = true }
errors = { workspace = true }
external_identifier = { workspace = true }
feature_flags = { workspace = true }
http_server = { workspace = true }
instrumentation = { workspace = true }
notification = { workspace = true }
privileged_action = { workspace = true }
recovery = { workspace = true }
types = { workspace = true, features = ["account", "privileged_action"] }
userpool = { workspace = true }
wsm-rust-client = { workspace = true }

# temporary dependencies (for fake wsm)
base64 = { workspace = true }
crypto = { workspace = true, features = ["serde"] }
