[package]
edition = { workspace = true }
name = "external_identifier"
publish = { workspace = true }
version = "0.1.0"

[dependencies]
thiserror = { workspace = true }
urn = { workspace = true }

[lints]
workspace = true
