[package]
edition = { workspace = true }
name = "types"
publish = { workspace = true }
version = "0.1.0"

[dependencies]
base32 = { workspace = true }
derive_builder = { workspace = true }
once_cell = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = "0.10.8"
strum = { workspace = true }
strum_macros = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
tokio = { workspace = true }
ulid = { workspace = true }
urn = { workspace = true }
utoipa = { workspace = true }

# path dependencies
bdk_utils = { workspace = true }
external_identifier = { workspace = true }

[features]
account = []
all = [
  "account",
  "authn_authz",
  "consent",
  "currencies",
  "exchange_rate",
  "notification",
  "privileged_action",
  "recovery",
  "serde",
]
authn_authz = []
consent = []
currencies = []
exchange_rate = []
notification = []
privileged_action = []
recovery = []
serde = []
